# Crear Admin
# POST http://localhost:3000/api/v1/admin/register
# Content-Type: application/json

# {
#   "name": "Admin Test",
#   "email": "admin1@test.com",
#   "password": "admin123",
#   "phone": "+528681252525",
#   "logoUrl": "http://example.com/avatar.jpg",
#   "gender": "male"
# }


# Login Admin

# POST http://localhost:3000/api/v1/admin/login
# Content-Type: application/json

# {
#   "email": "admin1@test.com",
#   "password": "admin123"
# }


# Crear empresa
# POST http://localhost:3000/api/v1/empresa/register
# Content-Type: application/json
# Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWU0NTM3MDYwNjYyZTVlNGRiZjU0NyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0NzMyNTc3NiwiZXhwIjoxNzQ3NDEyMTc2fQ.n8YDFCN5dTZmwenA-Rj3jQOAbGNd6xZsc0CAYsiVzYY

# {
#   "logoUrl": "https://example.com/logo.png",
#   "tradeName": "Comercial Matamoros SA DE CV",
#   "rfc": "TEV010101AB1",
#   "email": "empresa@matamoros.com",
#   "phone": "+528681252536",
#   "password": "empresa123"
# }


# Login Empresa

# POST http://localhost:3000/api/v1/empresa/login
# Content-Type: application/json

# {
#   "email": "empresa@matamoros.com",
#   "password": "empresa123"
# }

# Crear Agente
# POST http://localhost:3000/api/v1/agente/register
# Content-Type: application/json
# Cookie: 

# {
#   "firstName": "Carlos",
#   "lastName": "Ramírez",
#   "gender": "male",
#   "startDate": "2023-08-01",
#   "email": "carlos.ramirez@cosafe.com",
#   "phone": "+525512345678",
#   "position": "Supervisor",
#   "password": "agente1234"
# }



# Login Agente

# POST http://localhost:3000/api/v1/agente/login
# Content-Type: application/json

# {
#   "email": "carlos.ramirez@cosafe.com",
#   "password": "agente1234"
# }

#Sesion activa cookies admin
# GET http://localhost:3000/api/v1/admin/session

#Sesion activa cookies agente   
# GET http://localhost:3000/api/v1/agente/session

#Sesion activa cookies empresa
# GET http://localhost:3000/api/v1/empresa/session

# Obtener empresa por id admin
# GET http://localhost:3000/api/v1/empresas?adminId=681e4537060662e5e4dbf547


PUT http://localhost:3000/api/v1/empresa/682d476aaa10a0fc04933c87
Content-Type: application/json

{
  "tradeName": "Cosafe SA de CV",
  "rfc": "TEV010101AB2",
  "email": "empresa@matamoros.com",
  "phone": "+528681245690",
  "password": "admin123",
  "logoUrl": "https://cosafeimg.nyc3.cdn.digitaloceanspaces.com/profile/1751913130910-logo.png"
}

